### ISSUE TITLE
BUG: No timeslots displayed in checkout

### ISSUE THREAD

**Issue by mlaurense** [Trunkrs/trunkrs-magento-2-plugin#41]
The new version only shows a delivery date, no delivery timeslot is being displayed:
![Schermafbeelding 2022-06-23 om 14 13 29](https://user-images.githubusercontent.com/16759472/175296727-8f466046-1fb5-45d9-a23a-52ceeadb9c80.png)

Also, the layout of the shipping method is slightly odd:
![Schermafbeelding 2022-06-23 om 14 13 08](https://user-images.githubusercontent.com/16759472/175296816-df5f8fae-abdf-4fd5-9d17-18554836a616.png)

**Comment by fmsthird** [comment]
Hi, I'm not sure if I get what you mean. But we only need to display the delivery date based on the available timeslot. 🙂 
For the second one, yes that's understandable but we intend to only display the Trunkrs brand same with the other Trunkrs plugin.

**Comment by mlaurense** [comment]
But how is the customer supposed to know when the package will be delivered? The previous version showed a text between which hours (e.g. between 17.00 and 20.00 hours).

**Comment by fmsthird** [comment]
Timeslot is added on v2.1.0 release.
